%  y1 = tau_pn_mn_1(1:end,1);
%  y2 = tau_pn_mn_1(1:end,2);
%  y3 = tau_pn_mn_1(1:end,3);
%  y4 = tau_pn_mn_1(1:end,4);
%  y5 = tau_pn_mn_1(1:end,5);
%  y6 = tau_pn_mn_1(1:end,6);
  y1 = f_pn_mn_1(1:end,1);
 y2 = f_pn_mn_1(1:end,2);
 y3 = f_pn_mn_1(1:end,3);
 y4 = f_pn_mn_1(1:end,4);
 y5 = f_pn_mn_1(1:end,5);
 y6 = f_pn_mn_1(1:end,6);
 s1 = (y1- mean(y1)) / std(y1);
s2 = (y2 - mean(y2)) / std(y2);
s3 = (y3 - mean(y3)) / std(y3);
s4 = (y4 - mean(y4)) / std(y4);
s5 = (y5 - mean(y5)) / std(y5);
s6 = (y6 - mean(y6)) / std(y6);
% Compute time lag between signals
[c1 lags1] = xcorr(y1, y2,'coeff');   %// Cross correlation
[c2 lags2] =xcorr(y1,y3,'coeff');
[c3 lags3] = xcorr(y1,y4,'coeff');
[c4 lags4] = xcorr(y1,y5,'coeff');
[c5 lags5] = xcorr(y1,y6,'coeff');
figure(8);
subplot(2,2,1);
plot(lags1,c1,'b*');
title('Cross Corr Axis 1 with Axis 2');
xlabel('Lag','FontSize',10);
ylabel('Correlation coeff.','FontSize',10);
%figure(9);
subplot(2,2,2);
%plot(lags2,c2,'b*-.');
plot(lags2,c2,'b*');
xlabel('Lag','FontSize',10);
ylabel('Correlation coeff.','FontSize',10);
title('Cross Corr Axis 1 with Axis 3');
%figure(10);
subplot(2,2,3);
 
plot(lags3,c3,'b*');
title('Cross Corr Axis 1 with Axis 4');
xlabel('Lag','FontSize',10);
ylabel('Correlation coeff.','FontSize',10);
%figure(11);
subplot(2,2,4);
plot(lags4,c4,'b*');
title('Cross Corr Axis 1 with Axis 5');
xlabel('Lag','FontSize',10);
ylabel('Correlation coeff.','FontSize',10);
figure(12);
%subplot(3,2,5);
plot(lags5,c5,'b*');
title('Cross Corr Axis 1 with Axis 6');
xlabel('Lag','FontSize',10);
ylabel('Correlation coeff.','FontSize',10);